// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kaplay from "./Kaplay.res.mjs";
import * as Constants from "./Constants.res.mjs";
import * as GameContext from "./GameContext.res.mjs";

Kaplay.PosComp({});

Kaplay.RectComp({});

Kaplay.ColorComp({});

Kaplay.AreaComp({});

Kaplay.ZComp({});

function make(snakeHead, snakeTail) {
  let randomPos = () => {
    let max = Constants.gameSizeF - Constants.tileSize;
    let randomX = GameContext.k.rand(Constants.tileSize, max);
    let valueX = randomX - randomX % Constants.tileSize;
    let randomY = GameContext.k.rand(Constants.tileSize, max);
    let valueY = randomY - randomY % Constants.tileSize;
    return GameContext.k.vec2(valueX, valueY);
  };
  let isGoodPosition = pos => {
    if (snakeHead.hasPoint(pos)) {
      return false;
    } else {
      return snakeTail.every(tailPart => !tailPart.hasPoint(pos));
    }
  };
  let coinPos = () => {
    while (true) {
      let pos = randomPos();
      if (isGoodPosition(pos)) {
        return pos;
      }
      continue;
    };
  };
  GameContext.k.add([
    GameContext.k.rect(Constants.tileSize, Constants.tileSize),
    GameContext.k.color(Constants.yellow300),
    GameContext.k.pos(coinPos()),
    GameContext.k.area(),
    "Coin"
  ]);
}

export {
  make,
}
/*  Not a pure module */
