// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GameContext from "./GameContext.res.mjs";

let tileSizeVector = GameContext.k.vec2(25, 25);

let grey400 = GameContext.k.Color.fromHex("#99a1af");

let red500 = GameContext.k.Color.fromHex("#fb2c36");

let red600 = GameContext.k.Color.fromHex("#e7000b");

let yellow300 = GameContext.k.Color.fromHex("#ffdf20");

let neutral700 = GameContext.k.Color.fromHex("#404040");

let gameSize = 500;

let gameSizeF = 500.0;

let tileSize = 25;

let initialGameSpeed = 0.50;

export {
  gameSize,
  gameSizeF,
  tileSize,
  tileSizeVector,
  initialGameSpeed,
  grey400,
  red500,
  red600,
  yellow300,
  neutral700,
}
/* tileSizeVector Not a pure module */
