// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kaplay from "./Kaplay.res.mjs";
import * as Constants from "./Constants.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

Kaplay.AreaComp({});

function make() {
  return GameContext.k.add([GameContext.k.area({
      shape: Primitive_option.some(Kaplay.mathRect(GameContext.k, Constants.tileSizeVector, Constants.gameSizeF - 2 * Constants.tileSize, Constants.gameSizeF - 2 * Constants.tileSize))
    })]);
}

export {
  make,
}
/*  Not a pure module */
