// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.res.mjs";
import * as Area$Kaplay from "@nojaf/rescript-kaplay/src/Components/Area.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as Context$Kaplay from "@nojaf/rescript-kaplay/src/Context.res.mjs";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

Area$Kaplay.Comp({});

function make() {
  return GameContext.k.add([GameContext.k.area({
      shape: Primitive_option.some(Context$Kaplay.mathRect(GameContext.k, Constants.tileSizeVector, Constants.gameSizeF - 2 * Constants.tileSize, Constants.gameSizeF - 2 * Constants.tileSize))
    })]);
}

export {
  make,
}
/*  Not a pure module */
