// Generated by ReScript, PLEASE EDIT WITH CARE


let Debug = {};

let Vec2 = {};

let Color = {};

function TimerControllerImpl(T) {
  return {};
}

let TimerController = {};

let Shape = {};

let $$Math = {
  Shape: Shape
};

let mathRect = (function (k, pos, width, height) {
    return new k.Rect(pos, width, height);
});

let mathCircle = (function (k, center, radius) {
    return new k.Circle(center, radius);
});

let mathPolygon = (function (k,  points) {
    return new k.Polygon(points);
});

let Collision = {};

function GameObjRaw(T) {
  return {};
}

function PosComp(T) {
  return {};
}

function RectComp(T) {
  return {};
}

function CircleComp(T) {
  return {};
}

function ColorComp(T) {
  return {};
}

function OutlineComp(T) {
  return {};
}

function OpacityComp(T) {
  return {};
}

function SpriteComp(T) {
  return {};
}

function AnchorComp(T) {
  return {};
}

function BodyComp(T) {
  return {};
}

function AgentComp(T) {
  return {};
}

function SentryComp(T) {
  return {};
}

function AreaComp(T) {
  return {};
}

function HealthComp(T) {
  return {};
}

function TextComp(T) {
  return {};
}

function OffScreenComp(T) {
  return {};
}

function MoveComp(T) {
  return {};
}

function TileComp(T) {
  return {};
}

function ZComp(T) {
  return {};
}

let AudioPlay = {};

let TweenController = {};

let Level = {};

export {
  Debug,
  Vec2,
  Color,
  TimerControllerImpl,
  TimerController,
  $$Math,
  mathRect,
  mathCircle,
  mathPolygon,
  Collision,
  GameObjRaw,
  PosComp,
  RectComp,
  CircleComp,
  ColorComp,
  OutlineComp,
  OpacityComp,
  SpriteComp,
  AnchorComp,
  BodyComp,
  AgentComp,
  SentryComp,
  AreaComp,
  HealthComp,
  TextComp,
  OffScreenComp,
  MoveComp,
  TileComp,
  ZComp,
  AudioPlay,
  TweenController,
  Level,
}
/* No side effect */
