// Generated by ReScript, PLEASE EDIT WITH CARE


function make(maxSize) {
  return {
    items: [],
    maxSize: maxSize
  };
}

function enqueue(t, item) {
  t.items.push(item);
  if (t.items.length > t.maxSize) {
    t.items.shift();
    return;
  }
  
}

function dequeue(t) {
  return t.items.shift();
}

function peek(t) {
  return t.items[0];
}

export {
  make,
  enqueue,
  dequeue,
  peek,
}
/* No side effect */
