// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kaplay from "./Kaplay.res.mjs";
import * as Constants from "./Constants.res.mjs";
import * as GameContext from "./GameContext.res.mjs";

Kaplay.PosComp({});

Kaplay.RectComp({});

Kaplay.ColorComp({});

Kaplay.AreaComp({});

function make(x, y, tag) {
  return GameContext.k.add([
    GameContext.k.pos(x, y),
    GameContext.k.rect(Constants.tileSize, Constants.tileSize),
    GameContext.k.color(tag === "SnakeHead" ? Constants.red500 : Constants.red600),
    GameContext.k.area(),
    tag
  ]);
}

export {
  make,
}
/*  Not a pure module */
