// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Constants from "./Constants.res.mjs";
import * as Pos$Kaplay from "@nojaf/rescript-kaplay/src/Components/Pos.res.mjs";
import * as GameContext from "./GameContext.res.mjs";
import * as Text$Kaplay from "@nojaf/rescript-kaplay/src/Components/Text.res.mjs";
import * as Color$Kaplay from "@nojaf/rescript-kaplay/src/Components/Color.res.mjs";
import * as Anchor$Kaplay from "@nojaf/rescript-kaplay/src/Components/Anchor.res.mjs";

Text$Kaplay.Comp({});

Color$Kaplay.Comp({});

Pos$Kaplay.Comp({});

Anchor$Kaplay.Comp({});

function make(text, size, x, y) {
  return GameContext.k.add([
    GameContext.k.text(text, {
      size: size
    }),
    GameContext.k.pos(x, y),
    GameContext.k.anchor("center"),
    GameContext.k.color(Constants.neutral700)
  ]);
}

export {
  make,
}
/*  Not a pure module */
