// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kaplay from "./Kaplay.res.mjs";
import * as Constants from "./Constants.res.mjs";
import * as GameContext from "./GameContext.res.mjs";

Kaplay.TextComp({});

Kaplay.ColorComp({});

Kaplay.PosComp({});

Kaplay.AnchorComp({});

function make(text, size, x, y) {
  return GameContext.k.add([
    GameContext.k.text(text, {
      size: size
    }),
    GameContext.k.pos(x, y),
    GameContext.k.anchor("center"),
    GameContext.k.color(Constants.neutral700)
  ]);
}

export {
  make,
}
/*  Not a pure module */
