// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kaplay from "./Kaplay.res.mjs";
import * as Constants from "./Constants.res.mjs";
import * as GameContext from "./GameContext.res.mjs";

Kaplay.PosComp({});

Kaplay.RectComp({});

Kaplay.ColorComp({});

function make(x, y, width, height) {
  return GameContext.k.add([
    GameContext.k.pos(x, y),
    GameContext.k.rect(width, height),
    GameContext.k.color(Constants.grey400)
  ]);
}

export {
  make,
}
/*  Not a pure module */
